spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProyectoSoftware
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: asapsitterapp@gmail.com
    password: xecepobgdgtwcnnk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

